#!/usr/bin/env bash
#
# Usage:
#
#       $1 - Email of box user
#
# Example
#
#       box set-user-email "luke@theforce.org"
#

echo_if_not_quiet "$*" "=Setting user.email = '$1'..."
set_user_var "email" "$1" --quiet || return $?
git config --global user.email "$1" || return $?


