#!/bin/bash

source /opt/box/includes/functions
source /opt/box/includes/constants

case $1 in
	'info')
		echo "`basename $0`	- Test: Startup all containers."
		exit 42
		;;
esac

. ${WPLIB_BOX_CLI_DIR}/commands/test

echo_info "Check /var/www mountpoints."
exec_cmd ${WPLIB_BOX_CLI_DIR}/commands/check-mounts


echo_info "Check Docker can stop and start."
if [ -e /var/run/docker.sock ]
then
	exec_cmd service docker stop
fi

exec_cmd service docker start
exec_cmd docker info


