#!/bin/bash

source /opt/box/includes/functions
source /opt/box/includes/constants

case $1 in
	'info')
		echo "`basename $0`	- Test: Shutdown all containers."
		exit 42
		;;
esac

. ${WPLIB_BOX_CLI_DIR}/commands/test


exec_cmd docker container ls -q

exec_cmd box shutdown

exec_cmd docker container ls -q
if [ -s $EXECTMPFILE ]
then
	echo_error "Some containers couldn't shutdown."
	echo "$EXECTMPFILE"
	ls -l $EXECTMPFILE
	cat $EXECTMPFILE
	exec_cmd box container ls
fi


exit 0

