#!/bin/bash

function setup() {

}

function tests() {
    resultEquals "get_image_name wplib/mysql:5.5.60 60" "wplib/mysql:5.5.60"
    resultEquals "get_image_name mysql:5.5.60       60" "wplib/mysql:5.5.60"
    resultEquals "get_image_name mysql:5.5.59       60" "wplib/mysql:5.5.59"
    resultEquals "get_image_name mysql-5.5.60       60" "wplib/mysql:5.5.60"
    resultEquals "get_image_name mysql:5.5          60" "wplib/mysql:5.5.60"
    resultEquals "get_image_name mysql-5.5          60" "wplib/mysql:5.5.60"

    resultEquals "get_image_name wplib/php-fpm:7.1.17 17" "wplib/php-fpm:7.1.17"
    resultEquals "get_image_name php-fpm:7.1.17       17" "wplib/php-fpm:7.1.17"
    resultEquals "get_image_name php-fpm:7.1.16       17" "wplib/php-fpm:7.1.16"
    resultEquals "get_image_name php-fpm-7.1.17       17" "wplib/php-fpm:7.1.17"
    resultEquals "get_image_name php-fpm:7.1          17" "wplib/php-fpm:7.1.17"
    resultEquals "get_image_name php-fpm-7.1          17" "wplib/php-fpm:7.1.17"

    resultEquals "get_container_name wplib/mysql:5.5.60 60" "mysql-5.5.60"
    resultEquals "get_container_name mysql:5.5.60       60" "mysql-5.5.60"
    resultEquals "get_container_name mysql:5.5.59       60" "mysql-5.5.59"
    resultEquals "get_container_name mysql-5.5.60       60" "mysql-5.5.60"
    resultEquals "get_container_name mysql-5.5          60" "mysql-5.5.60"

    resultEquals "get_container_name wplib/php-fpm:7.1.17 17" "php-fpm-7.1.17" 
    resultEquals "get_container_name php-fpm:7.1.17       17" "php-fpm-7.1.17"
    resultEquals "get_container_name php-fpm:7.1.16       17" "php-fpm-7.1.16"
    resultEquals "get_container_name php-fpm-7.1.17       17" "php-fpm-7.1.17"
    resultEquals "get_container_name php-fpm-7.1          17" "php-fpm-7.1.17"

    resultNotEmpty 'docker container ls -aq -f "status=running" "$1"' 'Container $1 not running'
}

function containerStartsTest() {
    box container start $1

    valueNotEmpty "$1" "You did not pass a valid parameter."

    assertEquals "$1" "foobar"
    assertContains "$1" ":" "Container $1 is not in correct format"
    
    box container stop
}

function teardown() {

}


