#!/usr/bin/env bash

function boxStatus_Test() {
    local output="$(box status)"

    if [ -z "${output}" ]; then
        echo "The command [box status] produced no output."
        return 1
    fi
    local prefix="The output of [box status]"

    recordSuccess

    local dl="Downloaded components:"
    if ! StrContains "${output}" "${dl}"; then
        echo "${prefix} did not contain: ${dl}."
        return 1
    fi
    recordSuccess

    local sc="Stopped components:"
    if ! StrContains "${output}" "${sc}"; then
        echo "${prefix} did not contain: ${sc}."
        return 1
    fi
    recordSuccess

    local rc="Running components:"
    if ! StrContains "${output}" "${rc}"; then
        echo "${prefix} did not contain: ${rc}."
        return 1
    fi

    #recordSuccess - Framework will record one success
    return 0

}


