#!/usr/bin/env bash
#
# Download Plugin
#
exit_if_wp_not_installed "Cannot download plugin."

root_url="https://downloads.wordpress.org/plugin"

plugin_name="$1"
plugin_dir="${WPLIB_BOX_PLUGINS_DIR}/${plugin_name}"
if [ "$2" == "" ]; then
    plugin_version=""
else
    plugin_version=".$2"
fi

if [ -d "${plugin_dir}" ]; then
    exit_if_no_force_option "$3" "Plugin directory ${plugin_dir} already exists."
fi

plugin="${plugin_name}${plugin_version}"

echo_if_not_quiet "$*", "=Downloading plugin ${plugin}..."

plugin_zip="${plugin}.zip"
plugin_url="${root_url}/${plugin_zip}"
download_dir="/tmp/wplib-box-downloads-${RANDOM}"

mkdir -p "${download_dir}"
cd "${download_dir}"

wget "${plugin_url}"
unzip "${plugin}"
rm "${plugin_zip}"

rm -rf "${plugin_dir}" 2> /dev/null
mv "${plugin_name}" "${WPLIB_BOX_PLUGINS_DIR}"

cd "${PROJECT_BASE}/${CURRENT_PROJECT}"
rm -rf "${download_dir}"

echo_if_not_quiet "$*", "=Downloading complete."
