#!/bin/bash
#
# Update WPLib Box scripts.
#
# This script will handle having itself updated by creating a secondary script that contains
# all the git commands.
# This will be exec at the very end ensuring itself wont be changed during the update.


# Don't reference common variables as they may not exist.
WPLIB_BOX_SCRIPTS_REPO="https://github.com/wplib/box-scripts"
WPLIB_BOX_CLI_DIR="/opt/box"
DEFAULT_VERSION="master"


# Determine version to run.
if [ "$1" == "" ]
then
	VERSION="`cat ${WPLIB_BOX_CLI_DIR}/version`"
	if [ "$DEFAULT_VERSION" == "" ]
	then
		VERSION=${DEFAULT_VERSION}
	fi
else
	VERSION="$1"
fi


# Pull from GitHub.
if [ -d ${WPLIB_BOX_CLI_DIR} ]
then
	cat <<EOF > /tmp/self-update.$$
	cd ${WPLIB_BOX_CLI_DIR}
	echo "# WPLib-Box: Updating /opt/box with version ${VERSION}"
	sudo git config --global user.email "user@wplib.com"
	sudo git config --global user.name "WPLib"
	sudo git clean -q -d -fx "" > /dev/null
	sudo git pull > /dev/null 2>&1
	sudo git checkout -q --force ${VERSION} > /dev/null
	echo $VERSION > /opt/box/version
	echo "Done"
EOF
else
	cat <<EOF > /tmp/self-update.$$
	echo "# WPLib-Box: Initializing /opt/box with version ${VERSION}"
	sudo git clone -q ${WPLIB_BOX_SCRIPTS_REPO} ${WPLIB_BOX_CLI_DIR} > /dev/null
	echo $VERSION > /opt/box/version
	echo "Done"
EOF
fi

chmod a+x /tmp/self-update.$$
exec /tmp/self-update.$$
