#!/bin/bash
#
# Update WPLib Box scripts.
#
# This script will handle having itself updated by creating a secondary script that contains
# all the git commands.
# This will be exec at the very end ensuring itself wont be changed during the update.


# Don't reference common variables as they may not exist.
WPLIB_BOX_SCRIPTS_REPO="https://github.com/wplib/box-scripts"
WPLIB_BOX_CLI_DIR="/opt/box"
WPLIB_BOX_CLI_VERSION_FILE="/opt/box/version"
DEFAULT_VERSION="master"


# Determine version to run.
if [ "$1" == "" ]
then
	VERSION="$(cat "${WPLIB_BOX_CLI_VERSION_FILE}")"
	if [ "$DEFAULT_VERSION" == "" ]
	then
		VERSION=${DEFAULT_VERSION}
	fi
else
	VERSION="$1"
fi

echo "# WPLib-Box: Updating ${WPLIB_BOX_CLI_DIR} with version ${VERSION}"
if [ -d "${WPLIB_BOX_CLI_DIR}" ]
then
	if [ -d "${WPLIB_BOX_CLI_DIR}-LAST" ]
	then
		sudo rm -rf "${WPLIB_BOX_CLI_DIR}-LAST"
	fi
	sudo mv "${WPLIB_BOX_CLI_DIR}" "${WPLIB_BOX_CLI_DIR}-LAST"
fi
sudo mkdir -p ${WPLIB_BOX_CLI_DIR}
sudo git clone -q ${WPLIB_BOX_SCRIPTS_REPO} ${WPLIB_BOX_CLI_DIR} > /dev/null
cd ${WPLIB_BOX_CLI_DIR}
sudo git checkout -q --force ${VERSION} > /dev/null

if [ ! -f "${WPLIB_BOX_CLI_VERSION_FILE}" ]
then
	sudo touch "${WPLIB_BOX_CLI_VERSION_FILE}"
	sudo chown vagrant:vagrant "${WPLIB_BOX_CLI_VERSION_FILE}"
	echo $VERSION > "${WPLIB_BOX_CLI_VERSION_FILE}"
fi

sudo chown -R vagrant:vagrant "${WPLIB_BOX_CLI_DIR}"



exit
################################################################################
# Pull from GitHub.
if [ -d ${WPLIB_BOX_CLI_DIR} ]
then
	cat <<EOF > /tmp/self-update.$$
	cd ${WPLIB_BOX_CLI_DIR}
	echo "# WPLib-Box: Updating /opt/box with version ${VERSION}"
	sudo git config --global user.email "user@wplib.com"
	sudo git config --global user.name "WPLib"
	sudo git clean -q -d -fx "" > /dev/null
	sudo git pull -q ${WPLIB_BOX_SCRIPTS_REPO} > /dev/null 2>&1
	sudo git checkout -q --force ${VERSION} > /dev/null
	echo $VERSION > /opt/box/version
	echo "Done"
	rm /tmp/self-update.$$
EOF
else
	cat <<EOF > /tmp/self-update.$$
	echo "# WPLib-Box: Initializing /opt/box with version ${VERSION}"
	sudo git clone -q ${WPLIB_BOX_SCRIPTS_REPO} ${WPLIB_BOX_CLI_DIR} > /dev/null
	echo $VERSION > /opt/box/version
	echo "Done"
	rm /tmp/self-update.$$
EOF
fi

chmod a+x /tmp/self-update.$$
bash -x /tmp/self-update.$$
