#!/usr/bin/env bash
database="mysql"
webserver="nginx"
processvm="php7.0"
kvstore="redis"
if [ -f "/vagrant/project.json" ]; then
    database="$(jq -r '.services.database' < /vagrant/project.json)"
    webserver="$(jq -r '.services.webserver' < /vagrant/project.json)"
    processvm="$(jq -r '.services.processvm' < /vagrant/project.json)"
    kvstore="$(jq -r '.services.kvstore' < /vagrant/project.json)"
fi

docker stop ${database:-mysql} 2>&1 > /dev/null
docker stop ${webserver:-nginx} 2>&1 > /dev/null
docker stop ${kvstore:-redis} 2>&1 > /dev/null

if [ "php7.1" == $processvm ]; then
    if [ ! -f "/var/run/php/php7.1-fpm.pid" ]; then
        sudo service php7.1-fpm stop 2>&1 > /dev/null
    fi
else
    case $processvm in
        php5.6)
            processvm=php5_fpm
            ;;
        php7.0)
            processvm=php7_fpm
            ;;
    esac

    docker stop $processvm 2>&1 > /dev/null
fi
