#!/usr/bin/env bash

echo "Not yet implemented"
exit

echo_if_not_quiet "$*" "=Setting sites root on host..."


# Create NGINX config file
# -- Create sites-available
# -- Symlink sites-enabled

# Create Site Directory
# -- Setup WordPress unless --no-wp
# -- Create DB unless --no-db

# Update Vagrantfile
# Host updater


sudo service nginx reload

echo_if_not_quiet "$*" "^RELOAD Vagrant Done."

