#!/bin/bash
#
# Update WPLib Box scripts.
#


BASEDIR="${WPLIB_BOX_CLI_DIR}/scripts"

# Determine version to run.
if [ "$1" == "" ]
then
	VERSION="$BOX_VERSION"
else
	VERSION="$1"
fi

# Pull from GitHub.
if [ -d ${BASEDIR} ]
then
	cd ${BASEDIR}
	git clean -q -d  -fx ""
	git reset -q --hard $VERSION
	git pull
	git checkout -q $VERSION
else
	git clone "#{WPLIB_BOX_SCRIPTS_REPO}" "${WPLIB_BOX_CLI_DIR}"
fi

