#!/usr/bin/env bash

echo "Not yet implemented"
exit

echo_if_not_quiet "$*" "=Setting sites root on host..."

# Create/update the global config.json file.
if [ "" == "$1" ]; then
    echo "You must specify a path where your site subdirectories can found."
    return
fi

set_box_config "sites_dir", "$1"
sites_dir="$1"

echo_if_not_quiet "$*" "^WPLib Box sites directory on your host computer set to:\n\n\t${sites_dir}\n\nYou MUST run vagrant reload for this setting to take effect."


