#!/usr/bin/env bash

echo "Switching database server to $1"

if [ ! "mysql" == "$1" ] && [ ! "mariadb" == "$1" ]; then
    echo 'You must select either mysql or mariadb'
    exit 1
fi

converse="mariadb"
if [ 'mariadb' == $1 ]; then
    converse='mysql'
fi

sudo sed -i "s/${converse}/$1/" ${PROJECT_BASE}/${CURRENT_PROJECT}/project.json
mkdir -p ~/sql
mysqldump wordpress > ~/current.sql
docker stop $converse 2>&1 > /dev/null
sleep 5
docker start $1 2>&1 > /dev/null
sleep 10
mysql wordpress < ~/current.sql
rm ~/current.sql
