#!/bin/bash

declare="${BOX_CLI_DIR:=}"

source /opt/box/cli/includes/functions
case $1 in
	'info')
		echo "`basename $0`	- A simple Goodbye World test."
		exit 42
		;;
esac

echo "slater"
sleep 5
ls -l ${BOX_CLI_DIR}/commands
echo "done"

