#!/bin/bash

source /opt/box/cli/includes/functions
source /opt/box/cli/includes/constants

case $1 in
	'info')
		echo "`basename $0`	- A simple Goodbye World test."
		exit 42
		;;
esac

echo "slater"
sleep 5
ls -l ${WPLIB_BOX_CLI_DIR}/commands
echo "done"

