#!/bin/bash

source /opt/box/cli/includes/functions
source /opt/box/cli/includes/constants

case $1 in
	'info')
		echo "`basename $0`	- A no exec script"
		exit 42
		;;
esac

echo "You shouldn't ever see this script appear"

exit 7
