#!/usr/bin/env bash
#
# Backup the database to /vagrant/sql/current.sql
#
# Save the prior backup (if exists) to /vagrant/sql/previous.sql
# If /vagrant/sql/previous.sql save to /vagrant/sql/previous.2.sql, and so on.
#

bakfile="/vagrant/sql/current.sql"

#
# Check to see if we need to save a prior backup
#
if [[ -f "${bakfile}" ]]  ; then

    #
    # Get an unused backup file name
    #
    priorfile=$(next_backup_file "/vagrant/sql/previous.sql")

    #
    # Okay, we can now save the prior backup.
    #
    echo_if_not_quiet "$*", "=Saving Prior Backup as ${priorfile}..."
    cp "${bakfile}" "${priorfile}"

fi

echo_if_not_quiet "$*", "=Backing up database to ${bakfile}..."

mkdir -p /vagrant/sql

mysqldump -u wordpress -pwordpress wordpress > ${bakfile}





