#!/bin/bash
#
# Provisioning script for all containers.

DEFAULT_PROJECT="wplib"

# Colour codes.
GRAY="[30m"
RED="(B[m[31m"
GREEN="(B[m[32m"
YELLOW="(B[m[33m"
BLUE="(B[m[34m"
PURPLE="(B[m[35m"
CYAN="(B[m[36m"
DIRTYSNOW="(B[m[37m"
WHITE="(B[m[38m"
RESET="(B[m"

# Prefix used by all echo lines.
ECHO_PREFIX="$WHITE# WPLib-Box:$RESET"

# Return codes from functions.
RETURN_OK="0"
RETURN_NO_IMAGE_NAME="1"
RETURN_NO_LOCAL_IMAGE="2"
RETURN_NO_IMAGE_JSON="3"
RETURN_INVALID_PROJECT="4"


ctrl_c()
{
        tput sgr0
	echo ""
	echo "$ECHO_PREFIX Aborting script."
	exit
}

trap ctrl_c INT


error_pns()
{
	echo "$ECHO_PREFIX ${YELLOW}Warning project not supported${RESET}"
}

error_nip()
{
	echo "$ECHO_PREFIX ${RED}Error no image provided.${RESET}"
}

error_nfl()
{
	echo "$ECHO_PREFIX ${RED}Error ${CYAN}${IMAGE}${RED} image not found locally.${RESET}"
}

error_dnc()
{
	echo "$ECHO_PREFIX ${RED}Error ${CYAN}${IMAGE}${RED} image doesn't conform to JSON config format in 0.16 or later.${RESET}"
}

error_dni()
{
	echo "$ECHO_PREFIX ${RED}Error ${CYAN}${IMAGE}${RED} image does not exist in repository.${RESET}"
}

error_ccbr()
{
	echo "$ECHO_PREFIX ${RED}Error ${CYAN}${IMAGE}${RED} container can't be removed.${RESET}"
}

error_ccbi()
{
	echo "$ECHO_PREFIX ${RED}Warning ${CYAN}${IMAGE}${RED} container can't be installed.${RESET}"
}

error_ccbs()
{
	echo "$ECHO_PREFIX ${RED}Error ${CYAN}${IMAGE}${RED} container can't be started.${RESET}"
}

error_ccbd()
{
	echo "$ECHO_PREFIX ${RED}Error ${CYAN}${IMAGE}${RED} container can't be stopped.${RESET}"
}

error_cai()
{
	echo "$ECHO_PREFIX ${YELLOW}Warning ${CYAN}${IMAGE}${YELLOW} container already installed.${RESET}"
}

error_car()
{
	echo "$ECHO_PREFIX ${YELLOW}Warning ${CYAN}${IMAGE}${YELLOW} container already running.${RESET}"
}

error_cas()
{
	echo "$ECHO_PREFIX ${YELLOW}Warning ${CYAN}${IMAGE}${YELLOW} container already stopped.${RESET}"
}

error_csac()
{
	echo "$ECHO_PREFIX ${RED}Error not all containers could be stopped.${RESET}"
}


deets()
{
	if [ "$IMAGE" == "" ]
	then
		return $RETURN_NO_IMAGE_NAME
	fi

	RETURN="`docker image ls -q $IMAGE`"
	if [ "$RETURN" == "" ]
	then
		return $RETURN_NO_LOCAL_IMAGE
	fi

	DOCKER=`docker inspect --format='{{index .Config.Labels "container.project"}};{{index .Config.Labels "container.name"}};{{index .Config.Labels "container.version"}};{{index .Config.Labels "container.majorversion"}};{{index .Config.Labels "container.latest"}};{{index .Config.Labels "container.class"}};{{index .Config.Labels "container.network"}};{{index .Config.Labels "container.ports"}};{{index .Config.Labels "container.volumes"}};{{index .Config.Labels "container.restart"}};{{index .Config.Labels "container.args"}};{{index .Config.Labels "container.env"}}' $IMAGE`
	IFS=';' read -r -a state_array <<< "$DOCKER"

	PROJECT="${state_array[0]}"
	IMAGE_NAME="${state_array[1]}"
	IMAGE_VERSION="${state_array[2]}"
	IMAGE_MAJORVERSION="${state_array[3]}"
	IMAGE_LATEST="${state_array[4]}"
	IMAGE_CLASS="${state_array[5]}"
	IMAGE_NETWORK="${state_array[6]}"
	IMAGE_PORTS="${state_array[7]}"
	IMAGE_VOLUMES="${state_array[8]}"
	IMAGE_RESTART="${state_array[9]}"
	IMAGE_ARGS="${state_array[10]}"
	IMAGE_ENV="${state_array[11]}"

	if [ "$PROJECT" == "" ]
	then
		return $RETURN_NO_IMAGE_JSON
	fi
	if [ "$PROJECT" != "${DEFAULT_PROJECT}" ]
	then
		return $RETURN_INVALID_PROJECT
	fi


	CONTAINER_NAME="${IMAGE_NAME}-${IMAGE_VERSION}"
	CONTAINER_ID=`docker container ls -qaf name="${CONTAINER_NAME}"`
	if [ "$CONTAINER_ID" != "" ]
	then
		DOCKER="`docker inspect -f '{{.State.Running}};{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}};{{range .NetworkSettings.Networks}}{{(index .Aliases 0)}}{{end}}' $CONTAINER_NAME`"
		IFS=';' read -r -a state_array <<< "$DOCKER"

		CONTAINER_RUNNING="${state_array[0]}"
		CONTAINER_IP="${state_array[1]}"
		CONTAINER_HOSTNAME="${state_array[2]}"
	else
		CONTAINER_RUNNING=""
		CONTAINER_IP=""
		CONTAINER_HOSTNAME=""
	fi


	return $RETURN_OK
}


d_reallyclean()
{
	echo "${GREEN}Are you really sure? ${RED}Warning: this will remove ALL images and ALL data.${GREEN}"
	echo -n "Respond with ${YELLOW}Yes please${RESET}: "
	read RESPONSE
	if [ "$RESPONSE" == "Yes please" ]
	then
		echo -n "Please respond again with ${YELLOW}Yes please${RESET}: "
		read RESPONSE
		if [ "$RESPONSE" == "Yes please" ]
		then
			echo "$ECHO_PREFIX ${GREEN}Shutting down all WPLib containers.${RESET}"
			$0 container shutdown
			echo "$ECHO_PREFIX ${GREEN}Removing all WPLib containers.${RESET}"
			docker container ls -qaf "label=container.project=${DEFAULT_PROJECT}" | xargs -r docker container rm
			echo "$ECHO_PREFIX ${GREEN}Removing all WPLib images${RESET}"
			docker image ls -qaf "label=container.project=${DEFAULT_PROJECT}" | xargs -r docker image rm
		fi
	else
		echo "$ECHO_PREFIX ${GREEN}Doing nothing.${RESET}"
		echo "$ECHO_PREFIX If you want to really cleanup, then respond with ${YELLOW}Yes please${RESET}."
	fi
}


d_pull()
{
	echo "$ECHO_PREFIX ${GREEN}Pulling ${CYAN}$IMAGE${GREEN} from repository.${RESET}"
	docker pull $IMAGE
	if [ "$?" == "1" ]
	then
		error_dni
		return 1
	fi
}


d_install()
{
	deets $IMAGE
	RETURN="$?"
	case $RETURN in
		$RETURN_OK)
			if [ "$CONTAINER_HOSTNAME" != "" ]
			then
				error_cai
			else
				echo "$ECHO_PREFIX ${GREEN}Installing container: ${CYAN}${IMAGE}${RESET}"
				docker create --name ${CONTAINER_NAME} ${IMAGE_RESTART} ${IMAGE_NETWORK} ${IMAGE_PORTS} ${IMAGE_ARGS} ${IMAGE_VOLUMES} ${IMAGE}
				if [ "$?" == "1" ]
				then
					error_ccbi
				fi
			fi
			;;

		$RETURN_NO_LOCAL_IMAGE)
			error_nfl
			;;

		$RETURN_NO_IMAGE_JSON)
			error_dnc
			;;

		$RETURN_INVALID_PROJECT)
			error_pns
			;;
	esac

	return $RETURN
}


d_remove()
{
	deets $IMAGE
	RETURN="$?"
	case $RETURN in
		$RETURN_OK)
			echo "$ECHO_PREFIX ${GREEN}Removing container: ${CYAN}${IMAGE}${RESET}"
			docker rm -v ${CONTAINER_NAME}
			if [ "$?" == "1" ]
			then
				error_ccbr
			fi
			;;

		$RETURN_NO_LOCAL_IMAGE)
			error_nfl
			;;

		$RETURN_NO_IMAGE_JSON)
			error_dnc
			;;

		$RETURN_INVALID_PROJECT)
			error_pns
			;;
	esac

	return $RETURN
}


d_start()
{
	deets $IMAGE
	RETURN="$?"
	case $RETURN in
		$RETURN_OK)
			if [ "$CONTAINER_RUNNING" == "true" ]
			then
				error_car
			else
				echo "$ECHO_PREFIX ${GREEN}Starting container: ${CYAN}${IMAGE}${RESET}"
				docker start ${CONTAINER_NAME}
				if [ "$?" == "1" ]
				then
					error_ccbs
				fi
			fi
			;;

		$RETURN_NO_LOCAL_IMAGE)
			error_nfl
			;;

		$RETURN_NO_IMAGE_JSON)
			error_dnc
			;;

		$RETURN_INVALID_PROJECT)
			error_pns
			;;
	esac

	return $RETURN
}


d_stop()
{
	deets $IMAGE
	RETURN="$?"
	case $RETURN in
		$RETURN_OK)
			if [ "$CONTAINER_RUNNING" != "true" ]
			then
				error_cas
			else
				echo "$ECHO_PREFIX ${GREEN}Stopping container: ${CYAN}${IMAGE}${RESET}"
				docker stop ${CONTAINER_NAME}
				if [ "$?" == "1" ]
				then
					error_ccbd
				fi
			fi
			;;

		$RETURN_NO_LOCAL_IMAGE)
			error_nfl
			;;

		$RETURN_NO_IMAGE_JSON)
			error_dnc
			;;

		$RETURN_INVALID_PROJECT)
			error_pns
			;;
	esac

	return $RETURN
}


d_shutdown()
{
	echo "$ECHO_PREFIX ${GREEN}Stopping all WPLLib containers${RESET}"
	docker container ls -qaf "label=container.project=${DEFAULT_PROJECT}" | xargs docker stop
	if [ "$?" == "1" ]
	then
		error_csac
		return 1
	fi
}


d_ls()
{
	deets $IMAGE
	RETURN="$?"
	case $RETURN in
		$RETURN_OK)
			echo "$ECHO_PREFIX ${GREEN}Installed image: ${CYAN}${IMAGE}${RESET}"
			docker image ls $IMAGE
			echo ""
			echo "$ECHO_PREFIX ${GREEN}Installed container: ${CYAN}${IMAGE}${RESET}"
			docker container ls -af "name=${CONTAINER_NAME}"
			;;

		$RETURN_NO_IMAGE_NAME)
			echo "$ECHO_PREFIX ${GREEN}Installed images: ${CYAN}${IMAGE}${RESET}"
			docker image ls -af "label=container.project=$DEFAULT_PROJECT"
			echo ""
			echo "$ECHO_PREFIX ${GREEN}Installed containers: ${CYAN}${IMAGE}${RESET}"
			docker container ls -af "label=container.project=$DEFAULT_PROJECT" -f "status=created" -f "status=exited"
			echo ""
			echo "$ECHO_PREFIX ${GREEN}Running containers: ${CYAN}${IMAGE}${RESET}"
			docker container ls -af "label=container.project=$DEFAULT_PROJECT" -f "status=running"
			;;

		$RETURN_NO_LOCAL_IMAGE)
			error_nfl
			;;

		$RETURN_NO_IMAGE_JSON)
			error_dnc
			;;

		$RETURN_INVALID_PROJECT)
			error_pns
			;;
	esac

	return $RETURN
}


d_inspect()
{
	deets $IMAGE
	RETURN="$?"
	case $RETURN in
		$RETURN_OK)
			echo "$ECHO_PREFIX ${GREEN}Installed image: ${CYAN}${IMAGE}${RESET}"
			docker image inspect $IMAGE
			echo ""
			echo "$ECHO_PREFIX ${GREEN}Running container: ${CYAN}${IMAGE}${RESET}"
			docker container inspect ${CONTAINER_NAME}
			;;

		$RETURN_NO_LOCAL_IMAGE)
			error_nfl
			;;

		$RETURN_NO_IMAGE_JSON)
			error_dnc
			;;

		$RETURN_INVALID_PROJECT)
			error_pns
			;;
	esac

	return $RETURN
}


d_log()
{
	deets $IMAGE
	RETURN="$?"
	case $RETURN in
		$RETURN_OK)
			echo "$ECHO_PREFIX ${GREEN}Logs for container: ${CYAN}${IMAGE}${RESET}"
			docker container logs ${CONTAINER_NAME}
			;;

		$RETURN_NO_LOCAL_IMAGE)
			error_nfl
			;;

		$RETURN_NO_IMAGE_JSON)
			error_dnc
			;;

		$RETURN_INVALID_PROJECT)
			error_pns
			;;
	esac

	return $RETURN
}


d_help()
{
	cat <<EOF
box container [32minstall(B[m <package>	- Install and configure a container.
box container [32mls(B[m [package]	- List current image and container.
box container [32mstart(B[m <package>	- Start a container.
box container [32mstop(B[m <package>	- Stop a container.
box container [32mrm(B[m <package>	- Remove the container.
box container [32mclean(B[m <package>	- Remove the container and associated image.
box container [32mrefresh(B[m <package>	- Refresh an existing container.

box container [32mshutdown(B[m		- This will shutdown all WPLib related packages.
box container [32mreallyclean(B[m	- This will remove all WPLib related packages.
box container [32minspect(B[m <package>	- Provide detailed info on image and container.
box container [32mlog(B[m <package>	- Show log files from container.
box container [32mpull(B[m <package>	- Just pull a container image. No install.
EOF
}


################################################################################
CMD="$1"
shift
IMAGES="$@"

case $CMD in
	'show'|'list'|'ls')
		# Only the 'ls' command can accept no image.
		#echo "$@"
		if [ "$1" == "" ]
		then
			d_ls
		fi
		;;

	'reallyclean')
		d_reallyclean
		exit $?
		;;

	'shutdown')
		d_shutdown
		exit $?
		;;

	''|'help')
		d_help
		;;

	*)
		if [ "$1" == "" ]
		then
			error_nip
			d_help
			exit 1
		fi
		;;
esac


for IMAGE in $IMAGES
do
	case $CMD in
		'provision')
			echo "$ECHO_PREFIX ${GREEN}Provisioning ${CYAN}${IMAGE}.${RESET}"
			d_pull $IMAGE
			d_install $IMAGE
			d_start $IMAGE
			;;

		'refresh'|'upgrade')
			echo "$ECHO_PREFIX ${GREEN}Refreshing container: ${CYAN}${IMAGE}${RESET}"
			d_stop $IMAGE
			d_remove $IMAGE
			docker image rm $IMAGE

			d_install $IMAGE
			;;

		'clean')
			echo "$ECHO_PREFIX ${GREEN}Cleaning up: ${CYAN}${IMAGE}.${RESET}"
			d_stop $IMAGE
			d_remove $IMAGE
			docker image rm $IMAGE
			;;

		'pull')
			d_pull
			;;

		'create'|'install')
			d_pull
			d_install
			;;

		'remove'|'rm'|'destroy')
			d_remove
			;;

		'start'|'up')
			d_start
			;;

		'stop'|'down')
			d_stop
			;;

		'show'|'list'|'ls')
			d_ls
			;;

		'inspect'|'info')
			d_inspect
			;;

		'log')
			d_log
			;;
	esac
done


