#!/usr/bin/env bash
#
# Disable object caching for Redis using WP Redis plugin
#

exit_if_wp_not_installed "disable object caching."

object_cache_file_root="${WPLIB_BOX_CONTENT_DIR}/object-cache"
object_cache_file="${object_cache_file_root}.php"
disabled_object_cache_file="${object_cache_file_root}.disabled.php"

if [ ! -f "${object_cache_file}" ]; then
    echo "Object cache file ${object_cache_file} does not exists."
    echo "Object caching ALREADY disabled."
    exit
fi

rm "${disabled_object_cache_file}" 2> /dev/null

mv "${object_cache_file}" "${disabled_object_cache_file}"

echo "Object cache disabled."
echo "Object cache file renamed to ${disabled_object_cache_file}."



