#!/usr/bin/env bash
#
# Disassociate the github.com/wplib/wplib-box repo with this project
#

remotes=

if [[ remotes == *"git@github.com:wplib/wplib-box.git"* ]]; then

    echo_if_not_quiet "$*" "=This is not a WPLib Box Git repository. Maybe it was already disassociated?"
    return

fi

if [ -d "${WPLIB_BOX_ORIGINAL_GIT_DIR}" ]; then

    echo_if_not_quiet "$*" "=The directory "${WPLIB_BOX_ORIGINAL_GIT_DIR}" exists. Maybe it was already disassociated?"
    return

fi

#
# Change to /vagrant
#
cd "${WPLIB_BOX_DIR}" 2> /dev/null

#
# Move .git to .wplib-box.git
#
mv "${WPLIB_BOX_GIT_DIR}" "${WPLIB_BOX_ORIGINAL_GIT_DIR}" 2> /dev/null

#
# Create a new repo!
#
git init 2> /dev/null

#
# Remove /vagrant/watchers from .gitignore
# See http://stackoverflow.com/a/13188531/102699
#
grep -v "/vagrant/watchers" .gitignore > /tmp/.gitignore.tmp
mv /tmp/.gitignore.tmp .gitignore

echo_if_not_quiet "$*" "=The WPLib Box Git repository was disassociated."

