#!/usr/bin/env bash
#
# Import a database from /vagrant/sql/$1.sql
#
# Usage: box import-db {dump_file} [--echo] [--quiet]
#
#   Result ==> Imports from /vagrant/sql/{dump_file}.sql
#
#   --echo - Echos the backed-up filename
#   --quiet - Omits

importfile="$1"

if [ 'sql' != $(to_lowercase $(file_extension "${importfile}")) ]; then
    #
    # If no .sql extension, add one.
    #
    importfile="${importfile}.sql"
fi

#
# Force import from  /vagrant/sql/
#
importfile="${WPLIB_BOX_SQL_DIR}/${importfile}"

#
# Check to see if we need to import from exists
#
if [ ! -f "${importfile}" ]  ; then

    echo_if_not_quiet "$*", "=No ${importfile} exists.."
    return

fi

bakfile=$(box backup-db --quiet --echo-filename --dry-run)

if [ "${bakfile}" == "${importfile}" ]; then

    echo_if_not_quiet "$*", "^\tERROR:  The default backup filename is '$1'."
    echo_if_not_quiet "$*", "=\tCannot backup before import thus cannot continue."
    return

fi

echo_if_not_quiet "$*", "^Backing up database..."

bakfile=$(box backup-db --quiet --echo-filename)

if [ "" == "${bakfile}" ]; then

    echo_if_not_quiet "$*", "^Unknown error when generating the backup."
    return

fi

if [[ "$*" == *" error "* ]]; then

    echo_if_not_quiet "$*", "^Error when generating the backup: ${bakfile}"
    return

fi

echo_if_not_quiet "$*", "^Database backed-up to ${bakfile}..."

echo_if_not_quiet "$*", "=Importing database from ${importfile}..."

mysql -u wordpress -pwordpress wordpress < ${importfile}





