#!/usr/bin/env bash
#
# Import a database from /vagrant/sql/$1.sql
#
# Usage: box import-db {dump_file} [--echo] [--quiet]
#
#   Result ==> Imports from /vagrant/sql/{dump_file}.sql
#
#   --echo - Echos the backed-up filename
#   --quiet - Omits

importfile="$1"

if [ 'sql' != $(to_lowercase $(file_extension "${importfile}")) ]; then
    #
    # If no .sql extension, add one.
    #
    importfile="${importfile}.sql"
fi

#
# Force import from  /vagrant/sql/
#
importfile="${WPLIB_BOX_SQL_DIR}/${importfile}"

#
# Check to see if we need to import from exists
#
if [ ! -f "${importfile}" ]  ; then

    echo_if_not_quiet "$*", "=No ${importfile} exists.."
    return

fi

bakfile=$(box backup-db --quiet --echo-filename --dry-run)

if [ "${bakfile}" == "${importfile}" ]; then

    echo_if_not_quiet "$*", "=\tERROR: Cannot backup '$1' because the"
    echo_if_not_quiet "$*", "=\t       default backup filename is '$1'"
    echo_if_not_quiet "$*", "^\t       thus cannot backup before import."
    echo_if_not_quiet "$*", "=\t       Rename ${importfile} to "
    echo_if_not_quiet "$*", "=\t       bypass this check and allow import."
    return

fi

echo_if_not_quiet "$*", "=Backing up database..."

bakfile=$(box backup-db --quiet --echo-filename)

if [ "" == "${bakfile}" ]; then

    echo_if_not_quiet "$*", "^Unknown error when generating the backup."
    return

fi

if [[ "$*" == *" error "* ]]; then

    echo_if_not_quiet "$*", "^Error when generating the backup: ${bakfile}"
    return

fi

echo_if_not_quiet "$*", "^Database backed-up to ${bakfile}."

echo_if_not_quiet "$*", "=Dropping any prior tables..."
mysql -u wordpress -pwordpress -Nse "show tables;" wordpress 2>&1 | grep -v "Warning:" > /tmp/mysql-table-list.txt
cat /tmp/mysql-table-list.txt | while read table; do mysql -u wordpress -pwordpress -e "drop table $table" wordpress 2>&1 | grep -v "Warning:"; done
rm /tmp/mysql-table-list.txt
echo_if_not_quiet "$*", "^Tables dropped."

if [ "" != "$(cat "${importfile}" | grep "utf8mb4_unicode_520_ci")" ]; then
    #
    # MariaDB does not support 'utf8mb4_unicode_520_ci' but does support 'utf8mb4_unicode_ci'
    # This should become a lot more intelligent but for now it should suffice.
    #
    echo_if_not_quiet "$*", "=Stripping '520' from 'utf8mb4_unicode_520_ci' in ${importfile}..."
    sed -i -e 's/utf8mb4_unicode_520_ci/utf8mb4_unicode_ci/g' "${importfile}"
    echo_if_not_quiet "$*", "=520 stripped."
fi

echo_if_not_quiet "$*", "=Importing database from ${importfile}..."
mysql -u wordpress -pwordpress wordpress < ${importfile}  2>&1 | grep -v "Warning:"
echo_if_not_quiet "$*", "=Database imported."






