#!/usr/bin/env bash
#
# Install WP CLI support
#
# Usage: box install-wp-cli
#

echo "WPLib-Box: No longer required."
exit
export DEBIAN_FRONTEND=noninteractive
sudo ln -sf /usr/bin/php7.1 /etc/alternatives/php
sudo apt-get -y update
sudo apt-get -o Dpkg::Options::="--force-confnew" -y install --reinstall php7.1-bcmath php7.1-cli php7.1-common php7.1-curl php7.1-dev php7.1-fpm php7.1-gd php7.1-json php7.1-mbstring php7.1-mcrypt php7.1-mysql php7.1-opcache php7.1-pspell php7.1-readline php7.1-xml php7.1-zip
wp
