#!/usr/bin/env bash

package="${1%:*}"
version=`expr match "${1}" '.*\:\(*\)'`
version=${version:-master}
filename=${version:-master}.zip
directory=/tmp/${package##*\/}-${version}

#Download package
wget https://github.com/${package}/archive/${filename} -O /tmp/${filename}

if [ -f "/tmp/${filename}" ]; then
    unzip /tmp/${filename} -d /tmp

    # What major type (container, pkg, etc)
    # see http://stackoverflow.com/a/4170409
    type=$(jq -r ".type" ${directory}/installable.json)

    case "${type%\/*}" in
      container)
        source "${WPLIB_BOX_INCLUDES_DIR}/install-container" ${directory}/installable.json
        ;;
    esac

    error=0
else
    echo "Package not found. Specify a GitHub organization/repository name (e.g. wplib/caddy-package)."
    error=1
fi

#Clean up
if [ -f "${filename}" ]; then
    unlink ${filename}
fi

if [ -d "${directory}" ] ; then
    rm -rf ${directory}
fi

return ${error}
