#!/usr/bin/env bash
git clone https://github.com/$1 /tmp/package

# http://stackoverflow.com/questions/35005893/how-do-i-convert-json-array-to-bash-array-of-strings-with-jq
jq -r '.scripts[]' /tmp/package/installable.json | while read script; do
  sh /tmp/package/scripts/${script}
done

if [ -d "/tmp/package" ] ; then
  rm -rf /tmp/package
fi