#!/usr/bin/env bash
#
# Reassociate the github.com/wplib/wplib-box repo with this project
#

if [ ! -d "${WPLIB_BOX_ORIGINAL_GIT_DIR}" ]; then
    echo "WARNING: There is no WPLib Box .git directory (${WPLIB_BOX_ORIGINAL_GIT_DIR}) to reassociate."
    echo
    echo "Cannot continue."
    echo
    exit
fi

if [ -d "${WPLIB_BOX_SAVE_GIT_DIR}" ]; then
    echo "WARNING: There is already a Git Save directory (${WPLIB_BOX_SAVE_GIT_DIR}); delete to reassociate."
    echo "You MAY need to delete from your host computer's command line."
    echo
    echo "Cannot continue."
    echo
    exit
fi

mv "${WPLIB_BOX_GIT_DIR}" "${WPLIB_BOX_SAVE_GIT_DIR}"
mv "${WPLIB_BOX_ORIGINAL_GIT_DIR}/${WPLIB_BOX_FLAG_FILE}" "${WPLIB_BOX_FLAG_FILEPATH}"
mv "${WPLIB_BOX_ORIGINAL_GIT_DIR}" "${WPLIB_BOX_GIT_DIR}"

