#!/usr/bin/env bash
#
# Reassociate the github.com/wplib/wplib-box repo with this project
#

if [ ! -d "${WPLIB_BOX_ORIGINAL_GIT_DIR}" ]; then

    echo_if_not_quiet "$*" "=There is no original WPLib Box .git directory (${WPLIB_BOX_ORIGINAL_GIT_DIR}) to reassociate."
    return

fi

if [ -d "${WPLIB_BOX_SAVE_GIT_DIR}" ]; then

    echo_if_not_quiet "$*" "=There is already a Git Save directory (${WPLIB_BOX_SAVE_GIT_DIR}); delete to reassociate.\nYou MAY need to delete FROM your host computer's command line."
    return

fi

#
# Move .git to .save.git
#
mv "${WPLIB_BOX_GIT_DIR}" "${WPLIB_BOX_SAVE_GIT_DIR}" 2> /dev/null

#
# Move .wplib-box.git to .git
#
mv "${WPLIB_BOX_ORIGINAL_GIT_DIR}" "${WPLIB_BOX_GIT_DIR}" 2> /dev/null

#
# Add /vagrant/watchers to .gitignore if not already there.
#
grep -q -F "/vagrant/watchers" "${WPLIB_BOX_DIR}/.gitignore" || echo "/vagrant/watchers" >> ${WPLIB_BOX_DIR}/.gitignore


echo_if_not_quiet "$*" "=The WPLib Box Git repository has been reassociated and the prior .git directory has been renamed to ${WPLIB_BOX_SAVE_GIT_DIR} (assuming there was one.)"
