#!/usr/bin/env bash

echo "Switching web server to $1"

if [ ! "apache" == "$1" ] && [ ! "nginx" == "$1" ]; then
    echo 'You must select either nginx or apache'
    exit 1
fi

converse="apache"
if [ 'apache' == $1 ]; then
    converse='nginx'
fi

sudo sed -i "s/${converse}/$1/" /vagrant/box.json

docker stop $converse 2>&1 > /dev/null
docker start $1 2>&1 > /dev/null