#!/usr/bin/env bash

if [ "${WPLIB_BOX_WP_CONTENT_DIR}" == "/var/www/wp-content" ]; then

    echo_if_not_quiet "$*" "=WordPress directory structure is already in 'Standard' layout."

else

    cd /var/www
    mv wp/*.* .

    mv wp/wp-admin/ .
    mv wp/wp-includes/ .
    mv content/ wp-content/

    rm -rf wp/

    sed -i "s#/wp/wp-blog-header.php#/wp-blog-header.php#" index.php

    echo_if_not_quiet "$*" "=WordPress directory structure now set to 'Standard' layout."

fi



