#!/usr/bin/env bash

database="$(jq -r '.startup.database' < /vagrant/box.json)"
webserver="$(jq -r '.startup.webserver' < /vagrant/box.json)"
processvm="$(jq -r '.startup.processvm' < /vagrant/box.json)"

docker start $database \
  && docker start $webserver

if [ "php7.1_fpm" == $processvm ]; then
    sudo service php7.1-fpm start
else
    case "$processvm" in
        php7.0)
            processvm="php7_fpm"
            ;;

        php5.6)
            processvm="php5_fpm"
            ;;
    esac
    
    docker start $processvm
fi