#!/usr/bin/env bash
if [ -f "/vagrant/box.json" ]; then
    database="$(jq -r '.startup.database' < /vagrant/box.json)"
    webserver="$(jq -r '.startup.webserver' < /vagrant/box.json)"
    processvm="$(jq -r '.startup.processvm' < /vagrant/box.json)"
    object_cache="$(jq -r '.startup.object_cache' < /vagrant/box.json)"

    docker start $database \
      && docker start $webserver \
      && docker start $object_cache

    if [ "php7.1" == $processvm ]; then
        sudo service php7.1-fpm start
    else
        case "$processvm" in
            php7.0)
                processvm="php7_fpm"
                ;;

            php5.6)
                processvm="php5_fpm"
                ;;
        esac

        docker start $processvm
    fi
else
    docker start nginx
    docker start php7_fpm
    docker start mysql
    docker start redis
fi