#!/bin/bash
#
# Update WPLib-Box scripts.
#


BASEDIR="/opt/box/scripts"

# Determine version to run.
if [ "$1" == "" ]
then
	VERSION="$BOX_VERSION"
else
	VERSION="$1"
fi

# Pull from GitHub.
if [ -d ${BASEDIR} ]
then
	cd ${BASEDIR}
	git clean  -d  -fx ""
	git reset --hard $VERSION
	git pull
	git checkout -q $VERSION
else
	git clone https://github.com/wplib/box-scripts/ /opt/box/scripts
fi

