#!/usr/bin/env bash

export WPLIB_BOX_ARGS_ALL="$*"

export WPLIB_BOX_PHPCLI=$(which php7.0)

if [ "${PROJECT_BASE}" == "" ]
then
	PROJECT_BASE="/projects"
fi

if [ "${CURRENT_PROJECT}" == "" ]
then
	CURRENT_PROJECT="wplib.box"
fi

export WPLIB_BOX_PROJECT_BASE="${PROJECT_BASE}"
export WPLIB_BOX_CURRENT_PROJECT="${CURRENT_PROJECT}"

export WPLIB_BOX_DIR="${PROJECT_BASE}/${CURRENT_PROJECT}"
export WPLIB_BOX_BASE_DIR="/opt/box"
export WPLIB_BOX_CLI_DIR="${WPLIB_BOX_BASE_DIR}/cli"
export WPLIB_BOX_CLI_CMD="${WPLIB_BOX_BASE_DIR}/bin/box"
export WPLIB_BOX_WEB_ROOT_DIR="${PROJECT_BASE}/${CURRENT_PROJECT}/www"
export WPLIB_BOX_WATCHERS_DIR="${WPLIB_BOX_WEB_ROOT_DIR}/watchers"

export WPLIB_BOX_GIT_DIR="${WPLIB_BOX_DIR}/.git"
export WPLIB_BOX_LOGS_DIR="${WPLIB_BOX_DIR}/logs"
export WPLIB_BOX_SQL_DIR="${WPLIB_BOX_DIR}/sql"
export WPLIB_BOX_COMPOSER_FILE="${WPLIB_BOX_DIR}/composer.json"

export WPLIB_BOX_COMMANDS_DIR="${WPLIB_BOX_CLI_DIR}/commands"
export WPLIB_BOX_INCLUDES_DIR="${WPLIB_BOX_CLI_DIR}/includes"

export WPLIB_BOX_COLORS_FILE="${WPLIB_BOX_INCLUDES_DIR}/colors"

export WPLIB_BOX_FILES_DIR="${WPLIB_BOX_CLI_DIR}/files"

export WPLIB_BOX_SCRIPTS_REPO="https://github.com/wplib/box-scripts/"



#
# These need to be deprecated and replaced with project.json
#
export WPLIB_BOX_CONFIG="${WPLIB_BOX_DIR}/wplib.box.json"
export WPLIB_BOX_USER_CONFIG="${HOME}/wplib.box.json"
