#!/usr/bin/env bash


export BOX_NAME="wplib"

export BOX_ARGS_ALL="$*"

# Defines the root directory of all projects.
declare="${BOX_PROJECTS_ROOT:=/projects}"

# Defines the current project in use for a single project box.
declare="${BOX_CURRENT_PROJECT:=wplib.box}"

export BOX_CURRENT_PROJECT_DIR="${BOX_PROJECTS_ROOT}/${BOX_CURRENT_PROJECT}"

export BOX_USER="boxuser"
export BOX_USER_UID="1000"
export BOX_USER_GID="1000"
export BOX_USER_HOME="/home/box"
export BOX_USER_FILE="${BOX_USER_HOME}/user.json"

export BOX_PROJECT_DIR="${BOX_PROJECTS_ROOT}/${BOX_CURRENT_PROJECT}"

export BOX_BASE_DIR="/opt/box"
export BOX_CONFIG_FILE="${BOX_BASE_DIR}/box.json"

export BOX_VERSION="$(cat ${BOX_BASE_DIR}/version)"
export BOX_ETC_DIR="${BOX_BASE_DIR}/etc"
export BOX_RELEASES_DIR="${BOX_ETC_DIR}/releases"
export BOX_RELEASE_DIR="${BOX_RELEASES_DIR}/${BOX_VERSION}"
export BOX_RELEASE_JSON="${BOX_RELEASE_DIR}/project.json"
export BOX_CLI_DIR="${BOX_BASE_DIR}/cli"
export BOX_CLI_CMD="${BOX_BASE_DIR}/bin/box"
export BOX_WEB_ROOT_DIR="${BOX_CURRENT_PROJECT_DIR}/www"
export BOX_WATCHERS_DIR="${BOX_WEB_ROOT_DIR}/watchers"
export BOX_PHPCLI=${BOX_BASE_DIR}/bin/php
export BOX_CACHE_DIR="/tmp/box-cache"
mkdir -p "${BOX_CACHE_DIR}"

export BOX_GIT_DIR="${BOX_BASE_DIR}/.git"
export BOX_LOGS_DIR="${BOX_PROJECT_DIR}/logs"
export BOX_SQL_DIR="${BOX_PROJECT_DIR}/sql"
export BOX_SQL_PROVISION_LOCK="${BOX_PROJECT_DIR}.provisioned"
export BOX_COMPOSER_FILE="${BOX_PROJECT_DIR}/composer.json"
export BOX_PROJECT_FILE="${BOX_PROJECT_DIR}/project.json"


export BOX_COMMANDS_DIR="${BOX_CLI_DIR}/commands"
export BOX_INCLUDES_DIR="${BOX_CLI_DIR}/includes"

export BOX_COLORS_FILE="${BOX_INCLUDES_DIR}/colors"
export BOX_FUNCTIONS_FILE="${BOX_INCLUDES_DIR}/functions"

export BOX_FILES_DIR="${BOX_CLI_DIR}/files"

export BOX_TESTS_DIR="${BOX_CLI_DIR}/tests"

export BOX_SCRIPTS_REPO="https://github.com/wplib/box-scripts/"

mkdir -p /tmp/box-tmp
export DEPLOY_LOG="/tmp/box-tmp/deploy.log"
rm -rf "${DEPLOY_LOG}"


source ${BOX_INCLUDES_DIR}/colors


source ${BOX_INCLUDES_DIR}/general.functions
source ${BOX_INCLUDES_DIR}/container.functions


export BOX_CONTENT_DIR=$(find_wp_content_dir)
export BOX_PLUGINS_DIR=$(find_wp_plugins_dir)
export BOX_MU_PLUGINS_DIR=$(find_wp_mu_plugins_dir)
export BOX_VENDOR_DIR=$(find_composer_vendor_dir)
export BOX_ERROR_FILE="$(mktemp -d "/tmp/errors-XXXXX")/errors.txt"

#
# Source functions
#
source "${BOX_INCLUDES_DIR}/general.functions"
source "${BOX_INCLUDES_DIR}/container.functions"
source "${BOX_INCLUDES_DIR}/project-json.functions"
source "${BOX_INCLUDES_DIR}/git.functions"
source "${BOX_INCLUDES_DIR}/user.functions"
source "${BOX_INCLUDES_DIR}/template.functions"

