#!/usr/bin/env bash


export BOX_NAME="wplib"

export WPLIB_BOX_ARGS_ALL="$*"

if [ "${PROJECT_BASE}" == "" ]
then
	# Defines the root directory of all projects.
	PROJECT_BASE="/projects"
fi

if [ "${CURRENT_PROJECT}" == "" ]
then
	# Defines the current project in use for a single project box.
	CURRENT_PROJECT="wplib.box"
fi


export WPLIB_BOX_USER="boxuser"
export WPLIB_BOX_USER_UID="1000"
export WPLIB_BOX_USER_GID="1000"

export WPLIB_BOX_PROJECT_BASE="${PROJECT_BASE}"
export WPLIB_BOX_CURRENT_PROJECT="${CURRENT_PROJECT}"

export WPLIB_BOX_DIR="${PROJECT_BASE}/${CURRENT_PROJECT}"
export WPLIB_BOX_BASE_DIR="/opt/box"
export WPLIB_BOX_ETC="${WPLIB_BOX_BASE_DIR}/etc"
export WPLIB_BOX_CLI_DIR="${WPLIB_BOX_BASE_DIR}/cli"
export WPLIB_BOX_CLI_CMD="${WPLIB_BOX_BASE_DIR}/bin/box"
export WPLIB_BOX_WEB_ROOT_DIR="${PROJECT_BASE}/${CURRENT_PROJECT}/www"
export WPLIB_BOX_WATCHERS_DIR="${WPLIB_BOX_WEB_ROOT_DIR}/watchers"
export WPLIB_BOX_PHPCLI=${WPLIB_BOX_BASE_DIR}/bin/php

export WPLIB_BOX_GIT_DIR="${WPLIB_BOX_DIR}/.git"
export WPLIB_BOX_LOGS_DIR="${WPLIB_BOX_DIR}/logs"
export WPLIB_BOX_SQL_DIR="${WPLIB_BOX_DIR}/sql"
export WPLIB_BOX_COMPOSER_FILE="${WPLIB_BOX_DIR}/composer.json"

export WPLIB_BOX_COMMANDS_DIR="${WPLIB_BOX_CLI_DIR}/commands"
export WPLIB_BOX_INCLUDES_DIR="${WPLIB_BOX_CLI_DIR}/includes"

export WPLIB_BOX_COLORS_FILE="${WPLIB_BOX_INCLUDES_DIR}/colors"

export WPLIB_BOX_FILES_DIR="${WPLIB_BOX_CLI_DIR}/files"

export WPLIB_BOX_SCRIPTS_REPO="https://github.com/wplib/box-scripts/"


source ${WPLIB_BOX_INCLUDES_DIR}/colors

source ${WPLIB_BOX_INCLUDES_DIR}/general.functions
source ${WPLIB_BOX_INCLUDES_DIR}/container.functions


export WPLIB_BOX_CONTENT_DIR=$(find_wp_content_dir)
export WPLIB_BOX_PLUGINS_DIR=$(find_wp_plugins_dir)
export WPLIB_BOX_MU_PLUGINS_DIR=$(find_wp_mu_plugins_dir)
export WPLIB_BOX_VENDOR_DIR=$(find_composer_vendor_dir)


#
# These need to be deprecated and replaced with project.json
#
export WPLIB_BOX_CONFIG="${WPLIB_BOX_DIR}/wplib.box.json"
export WPLIB_BOX_USER_CONFIG="${HOME}/wplib.box.json"
