#!/usr/bin/env bash
#
# Example
#
#       box check-mounts
#
if [ -e ${PROJECT_BASE}/${CURRENT_PROJECT}/www/NOTMOUNTED ]
then
	tput setaf 1
	cat ${PROJECT_BASE}/${CURRENT_PROJECT}/www/index.txt
	tput sgr0
	exit 1
fi

exit 0

