#!/bin/bash
#
# Provisioning and management script for all containers.
#
# This is a low level script that will:
#	Pull the complete list of WPLib container packages from Docker Hub into local JSON files.
#	Manage containers - stop/start and most importantly creating containers using the embedded JSON string in the image.

source /opt/box/cli/includes/functions

# Return codes from functions.
RETURN_OK="0"
RETURN_NO_IMAGE_NAME="1"
RETURN_NO_LOCAL_IMAGE="2"
RETURN_NO_IMAGE_JSON="3"
RETURN_NO_IMAGE_REPO="4"
RETURN_INVALID_PROJECT="5"


ctrl_c()
{
        tput sgr0
	echo ""
	echo "$ECHO_PREFIX Aborting script."
	exit
}

trap ctrl_c INT


d_help()
{
	cat <<EOF
box container ${GREEN}install${RESET} <package>	- Install and configure a container.
box container ${GREEN}ls${RESET} [package]	- List current image and container.
box container ${GREEN}start${RESET} <package>	- Start a container.
box container ${GREEN}stop${RESET} <package>	- Stop a container.
box container ${GREEN}rm${RESET} <package>	- Remove the container.
box container ${GREEN}clean${RESET} <package>	- Remove the container and associated image.
box container ${GREEN}refresh${RESET} <package>	- Refresh an existing container.

box container ${GREEN}update${RESET}		- Update container list from repository.
box container ${GREEN}show${RESET}		- Show a list of containers available for download.
box container ${GREEN}shutdown${RESET}		- This will shutdown all WPLib related packages.
box container ${GREEN}reallyclean${RESET}	- This will remove all WPLib related packages.
box container ${GREEN}inspect${RESET} <package>	- Provide detailed info on image and container.
box container ${GREEN}log${RESET} <package>	- Show log files from container.
box container ${GREEN}pull${RESET} <package>	- Just pull a container image. No install.
EOF
}


################################################################################
CMD="$1"
shift
IMAGES="$@"

case $CMD in
	'list'|'ls')
		# Only the 'ls' command can accept no image.
		#echo "$@"
		if [ "$1" == "" ]
		then
			service_list
		fi
		;;

	'show')
		d_show
		exit $?
		;;

	'update')
		d_update
		exit $?
		;;

	'reallyclean')
		d_reallyclean
		exit $?
		;;

	'shutdown')
		d_shutdown
		exit $?
		;;

	'shell')
		IMAGE="$1"
		shift
		ARGS="$@"
		d_shell "$@"
		;;

	'exec')
		IMAGE="$1"
		shift
		ARGS="$@"
		d_exec "$@"
		;;

	''|'help')
		d_help
		;;

	*)
		if [ "$1" == "" ]
		then
			error_nip
			d_help
			exit 1
		fi
		;;
esac


for IMAGE in $IMAGES
do
	case $CMD in
		'refresh'|'upgrade')
			echo "$ECHO_PREFIX ${GREEN}Refreshing container: ${CYAN}${IMAGE}${RESET}"
			service_stop $IMAGE
			if [ "$?" == "$RETURN_OK" ]
			then
				service_remove $IMAGE
				if [ "$?" == "$RETURN_OK" ]
				then
					docker image rm -f $IMAGE
					if [ "$?" == "$RETURN_OK" ]
					then
						service_provision $IMAGE
					fi
				fi
			fi
			;;

		'clean')
			echo "$ECHO_PREFIX ${GREEN}Cleaning up: ${CYAN}${IMAGE}${RESET}"
			service_stop $IMAGE
			case $? in
				$RETURN_ALREADY_STOPPED|$RETURN_OK)
					service_remove $IMAGE
					if [ "$?" == "$RETURN_OK" ]
					then
						docker image rm -f $IMAGE
					fi
					;;
			esac
			;;

		'pull')
			service_image_pull $IMAGE
			;;

		'install')
			service_image_pull $IMAGE
			if [ "$?" == "$RETURN_OK" ]
			then
				service_create_container $IMAGE
			fi
			;;

		'provision')
			echo "$ECHO_PREFIX ${GREEN}Provisioning ${CYAN}${IMAGE}.${RESET}"
			service_provision $IMAGE
			;;

		'remove'|'rm'|'destroy')
			service_remove $IMAGE
			;;

		'start'|'up')
			service_start $IMAGE
			if [ "$?" == "$RETURN_NO_LOCAL_IMAGE" ]
			then
				service_provision $IMAGE
			else
				service_start $IMAGE
			fi
			;;

		'stop'|'down')
			service_stop $IMAGE
			;;

		'list'|'ls')
			service_list $IMAGE
			;;

		'inspect'|'info')
			d_inspect $IMAGE
			;;

		'log')
			d_log $IMAGE
			;;
	esac
done


