#!/usr/bin/env bash

declare="${GREEN:=}"
declare="${CYAN:=}"
declare="${YELLOW:=}"
declare="${RESET:=}"

cat <<EOF

${YELLOW}WPLib Box ${GREEN}CLI${RESET} usage:

box ${GREEN}component${RESET} [${CYAN}<args>{RESET}]	- Manage WPLib Box components
box ${GREEN}database${RESET} [${CYAN}<args>{RESET}]	- Manage databases.

box ${GREEN}startup${RESET}		- Start service components found in project.json's stack object.
box ${GREEN}restart${RESET}		- Restart service components found in project.json's stack object.
box ${GREEN}shutdown${RESET}		- Shutdown all Docker containers.

box ${GREEN}status${RESET}		- Output status of WPLib Box's standard service components.
box ${GREEN}version${RESET}		- Display the current version of this WPLib Box VM.
box ${GREEN}self-update${RESET}		- Update this CLI tool to the latest version for this Box version.

box ${GREEN}self-test${RESET} [${CYAN}<args>{RESET}]	- Run tests for WPLib Box itself
box ${GREEN}sync${RESET}                - Update box scripts in guest:/opt/box from host:/{project}/wplib.box/box

box [${GREEN}help${RESET}]		- Display the above information.
EOF
