#!/bin/bash

declare="${GREEN:=}"
declare="${CYAN:=}"
declare="${YELLOW:=}"
declare="${RESET:=}"


	cat <<EOF

${YELLOW}WPLib Box ${GREEN}Version Launch Checklist${RESET}

${CYAN}BEFORE DEVELOPMENT${RESET}
 - Decide on a release number.

 - Create a new branch with release number in repo:
   - https://github.com/wplib/wplib-box

 - Create a new milestone for the release:
   - https://github.com/wplib/wplib-box/milestones

 - Ensure there is a project that encompasses the release:
   - https://github.com/wplib/wplib-box/projects

 - Create a new version on VagrantCloud; leave unreleased
   - https://app.vagrantup.com/wplib/boxes/wplib

${CYAN}DURING DEVELOPMENT${RESET}
 - Create a "New Release" ticket like:
   - https://github.com/wplib/wplib-box/issues/533

 - Create a "Changelog" ticket like:
   - https://github.com/wplib/wplib-box/issues/532

 - Whittle down issues until there are none for version:
   - https://github.com/wplib/wplib-box/issues?q=is:open+is:issue+milestone:{version}

${CYAN}AT TIME OF RELEASE CANDIDATE${RESET}
 - Update existing tests based on changes

 - Write new tests to cover new features, changes.

 - Run build using Packer
   - https://github.com/newclarity/wplib-box-packer

 - Untar newly built box into global Vagrant directory:
   - ~/.vagrant.d/boxes/wplib-VAGRANTSLASH-wplib/{version}

 - Clone box from repo:
   - https://github.com/wplib/wplib-box

 - Checkout new version from clone:
   - git checkout -b {version} origin/{version}

 - Run Vagrant up and ssh into the box
   - vagrant up && vagrant ssh

 - Run all tests and ensure they pass:
   - box self-test run


${CYAN}AT TIME OF RELEASE${RESET}
 - Merge from version branch into master for this repo:
   - https://github.com/wplib/wplib-box

 - Write a CHANGELOG.

 - Update the version milestone with CHANGELOG
   - https://github.com/wplib/wplib-box/milestones/{milestone_id}/edit

 - Update the CHANGELOG in the repo:
   - https://github.com/wplib/wplib-box/blob/master/CHANGELOG.md

 - Update the CHANGELOG in VagrantCloud:
   - https://app.vagrantup.com/wplib/boxes/wplib/versions/{version}

 - Upload Vagrant VirtualBox provider to VagrantCloud:
   - https://app.vagrantup.com/wplib/boxes/wplib/versions/{version}

 - Add a New Release on GitHub w/CHANGELOG:
   - https://github.com/wplib/wplib-box/releases

 - Update download link:
   - https://wplib.github.io/box-docs/download/index.html


EOF
