#!/bin/bash
#
# Provisioning script that usually gets run after a `box self-update`
#
# This HAS to be run as root!

declare="${ECHO_PREFIX:=}"
declare="${GREEN:=}"
declare="${YELLOW:=}"
declare="${RESET:=}"
declare="${BOX_PROJECT_DIR:=}"
declare="${BOX_BASE_DIR:=}"
declare="${BOX_ETC:=}"
declare="${BOX_USER:=}"
declare="${BOX_USER_HOME:=}"
declare="${BOX_USER_UID:=}"
declare="${BOX_USER_GID:=}"
declare="${BOX_PROJECTS_ROOT:=}"
declare="${BOX_PROJECTS_ROOT:=}"
declare="${BOX_PROJECT_FILE:=}"
declare="${BOX_RELEASE_JSON:=}"
declare="${BOX_SQL_DIR:=}"
declare="${BOX_RELEASE_DIR:=}"

source /opt/box/cli/includes/functions

function ctrl_c()
{
    tput sgr0
	echo ""
	echo "$ECHO_PREFIX Aborting script."
	exit
}

trap ctrl_c INT


function HelpMe()
{
	cat <<EOF
box provision ${GREEN}check${RESET}		- Check everything is OK.
box provision ${GREEN}fix${RESET}		- Look for and fix issues.

EOF
}


# This is here for now, should be put somewhere else later.
function provision_fix()
{

	# First ensure home directory exists
	if [ ! -d "${BOX_PROJECT_DIR}/" ]
	then
		mkdir -p ${BOX_PROJECT_DIR}
	fi

	if [ ! -d /var/www ]
	then
		mkdir -p /var/www
	fi

	# Create symlinks
	link_file ${BOX_BASE_DIR}/etc/box-completion.bash /etc/bash_completion.d/box-completion.bash
	link_file ${BOX_BASE_DIR}/etc/box-profile.sh /etc/profile.d/box-profile.sh
	link_file ${BOX_BASE_DIR} /box

#	# Offer forwards / backwards compat.
#	if [ -L /vagrant ]
#	then
#		# We have a new layout - offer backwards compat.
#		link_file /projects/wplib.box /vagrant
#		link_file /projects/wplib.box/www /var/www
#	#else
#	#	# We have an old layout - offer forwards compat.
#	#	link_file /vagrant /projects/wplib.box
#	fi

	# cron jobs
	ln -sf ${BOX_ETC}/cron/${BOX_USER} /var/spool/cron/crontabs/${BOX_USER}

	# Setup boxuser, if not there.
	USERID="$(id -u ${BOX_USER})"
	if [ "${USERID}" == "" ]
	then
		useradd -o -d ${BOX_USER_HOME} -c "WPLib Box user" -u ${BOX_USER_UID} -g ${BOX_USER_GID} -N -s /bin/bash ${BOX_USER}
		usermod -aG docker ${BOX_USER}
	fi
	if [ ! -d ${BOX_USER_HOME}/.ssh ]
	then
		mkdir -pm 700 ${BOX_USER_HOME}/.ssh
	fi

	if [ ! -f ${BOX_USER_HOME}/.ssh/authorized_keys ]
	then
		wget -q --no-check-certificate 'https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub' -O ${BOX_USER_HOME}/.ssh/authorized_keys &>/dev/null
		chmod 0600 ${BOX_USER_HOME}/.ssh/authorized_keys
	fi
	touch ${BOX_USER_HOME}/.Xauthority

	# Change permissions.
	chown -R ${BOX_USER_UID}:${BOX_USER_GID} ${BOX_USER_HOME}
	chown -R ${BOX_USER_UID}:${BOX_USER_GID} ${BOX_BASE_DIR}
	chown ${BOX_USER_UID}:${BOX_USER_GID} ${BOX_PROJECTS_ROOT} ${BOX_PROJECTS_ROOT}/*

	cp ${BOX_ETC}/environment /etc/environment
	cp ${BOX_ETC}/inputrc /etc/inputrc
	cp ${BOX_BASE_DIR}/etc/box-aptget /etc/apt/apt.conf.d/42wplib
	rm -f /etc/update-motd.d/00-header /etc/update-motd.d/10-help-text /etc/update-motd.d/91-release-upgrade >& /dev/null
	link_file ${BOX_BASE_DIR}/etc/box-motd /etc/motd

	if [ ! -f "${BOX_PROJECT_FILE}" ]
	then
		cp ${BOX_RELEASE_JSON} ${BOX_PROJECT_FILE}
	fi

	if [ ! -f "${BOX_SQL_DIR}/provision.sql" ]
	then
		cp ${BOX_RELEASE_DIR}/sql/provision.sql ${BOX_SQL_DIR}/provision.sql
	fi
}


################################################################################
CMD="$1"
shift

case $CMD in
	'check')
		exit $?
		;;

	'fix')
		provision_fix
		exit $?
		;;

	''|'help')
		HelpMe
		;;

	*)
		if [ "$1" == "" ]
		then
			HelpMe
			exit 1
		fi
		;;
esac


