#!/bin/bash
#
# Update WPLib Box scripts.
#
# This script will handle having itself updated by creating a secondary script that contains
# all the git commands.
# This will be exec at the very end ensuring itself wont be changed during the update.


# Don't reference common variables as they may not exist.
WPLIB_BOX_SCRIPTS_REPO="https://github.com/wplib/box-scripts"
WPLIB_BOX_BASE_DIR="/opt/box"
DEFAULT_VERSION="master"


# Determine version to run.
if [ "$1" == "" ]
then
	VERSION="`cat ${WPLIB_BOX_BASE_DIR}/version`"
	if [ "$DEFAULT_VERSION" == "" ]
	then
		VERSION=${DEFAULT_VERSION}
	fi
else
	VERSION="$1"
fi


################################################################################
# Pull from GitHub.
if [ ! -d ${WPLIB_BOX_BASE_DIR} ]
then
	cat <<EOF > /tmp/self-update.$$
echo "# WPLib-Box: Initializing ${WPLIB_BOX_BASE_DIR} with version ${VERSION}"
sudo git clone -q ${WPLIB_BOX_SCRIPTS_REPO} ${WPLIB_BOX_BASE_DIR} > /dev/null

EOF
fi


cat <<EOF > /tmp/self-update.$$
cd ${WPLIB_BOX_BASE_DIR}
echo "# WPLib-Box: Updating ${WPLIB_BOX_BASE_DIR} with version ${VERSION}"

# Fetch the latest tags/branches.
git fetch -q --all
# Find any locally updated and tracked files - force overwrite.
git diff --name-only | xargs git checkout -q
# Add any locally updated and non-tracked files to the cache.
git add -A .
# Finally checkout the branch/tag.
git checkout -q ${VERSION} 2>/dev/null
echo "Done"
rm /tmp/self-update.$$
EOF


chmod a+x /tmp/self-update.$$
exec sudo /tmp/self-update.$$
