#!/bin/bash
#
# Master test script.
#

declare="${BOX_FUNCTIONS_FILE=}"
declare="${BOX_TESTS_DIR=}"
declare="${GREEN:=}"
declare="${CYAN:=}"
declare="${RESET:=}"

source "${BOX_FUNCTIONS_FILE}/includes/framework"
source "${BOX_TESTS_DIR}/includes/framework"

self_test_help() {
	cat <<EOF
box self-test 		- Show this help.

box self-test ${GREEN}list${RESET}		- List all self-tests in ${BOX_TESTS_DIR}.
box self-test ${GREEN}run${RESET}		- Run all self-tests in ${BOX_TESTS_DIR}.
box self-test ${GREEN}run ${CYAN}[script]${RESET}	- Run a specific self-test.
EOF
}

self_test_list() {
    find . -maxdepth 1 -type f | cut -c3-99
}

self_test_run() {
    if [ "" == "$1" ]; then
        test_RunAll
    else
        test_RunOne "$1"
    fi
}

################################################################################

CMD="$1"
shift

case $CMD in
	'list'|'ls')
		self_test_list
		;;

	''|'help')
		self_test_help
		;;

	'run')
		self_test_run "$1"
		;;

	*)
		self_test_help
		exit 1
		;;
esac

