#!/usr/bin/env bash

declare="${BOX_FUNCTIONS_FILE:=}"
source "${BOX_FUNCTIONS_FILE}"
source "${IMAGES:=}"

# Creates IMAGES and STACK env variables.
readJSON

box container stop ${IMAGES}
box container shutdown >& /dev/null
