#!/usr/bin/env bash

declare="${BOX_FUNCTIONS_FILE:=}"
declare="${IMAGES:=}"

source "${BOX_FUNCTIONS_FILE}"

# Creates IMAGES and STACK env variables.
readJSON

box container stop ${IMAGES}
box container shutdown >& /dev/null
