#!/usr/bin/env bash

declare="${IMAGES:=}"
declare="${BOX_FUNCTIONS_FILE:=}"

source "${BOX_FUNCTIONS_FILE}"

# Creates IMAGES and STACK env variables.
readJSON

case $1 in
	'-s'|'--short')
		box container start ${IMAGES} &>/dev/null
		box status --short
		;;

	*)
		box container start ${IMAGES}
		;;
esac

