#!/usr/bin/env bash

declare="${IMAGES:=}"

source /opt/box/cli/includes/functions

# Creates IMAGES and STACK env variables.
readJSON

case $1 in
	'-s'|'--short')
		box container start ${IMAGES} &>/dev/null
		box status --short
		;;

	*)
		box container start ${IMAGES}
		;;
esac

