#!/usr/bin/env bash

source /opt/box/cli/includes/functions

# Creates IMAGES and STACK env variables.
readJSON
# box container ls ${IMAGES}
# box container ls

echo "Components installed:"
echo $IMAGES | sed 's/wplib\//\n/g; s/:/\t/g'

