#!/usr/bin/env bash
#
# @see https://www.computerhope.com/unix/rsync.htm
#

source /opt/box/cli/includes/functions

if [ ! -d /projects/wplib.box/box ] ; then
    mkdir /projects/wplib.box/box
    rsync -aur /opt/box/* /projects/wplib.box/box
fi
trap "exit 0" SIGINT SIGTERM
counter=0
while true; do
    counter=$(( counter+1 ))
    printf "\rSyncing [${counter}]..."
    rsync --archive --recursive --links --safe-links --hard-links --keep-dirlinks --perms --times /projects/wplib.box/box/ /opt/box/
    sleep 1
done




