#!/usr/bin/env bash
#
# @see https://www.computerhope.com/unix/rsync.htm
#

source /opt/box/cli/includes/functions

if [ ! -d /projects/wplib.box/box ] ; then
    mkdir /projects/wplib.box/box
    rsync --archive --hard-links --perms --one-file-system /opt/box/ /projects/wplib.box/box
fi
trap "exit 0" SIGINT SIGTERM
counter=0
while true; do
    counter=$(( counter+1 ))
    printf "\rSyncing [${counter}]..."
    rsync --archive --hard-links --perms --recursive --links --safe-links --keep-dirlinks --times /projects/wplib.box/box/ /opt/box
    sleep 1
done




