#!/usr/bin/env bash
#
# Example
#
#       box version
#

source /opt/box/cli/includes/functions

case $1 in
	'-l')
		echo "WPLib: You are running version $(cat "${WPLIB_BOX_BASE_DIR}/version")"
		;;

	*)
		cat "${WPLIB_BOX_BASE_DIR}/version"
		;;
esac

