#!/usr/bin/env bash
#
# Example
#
#       box version
#
declare="${BOX_BASE_DIR:=}"

source /opt/box/cli/includes/functions

case $1 in
	'-s'|'--short')
		cat "${BOX_BASE_DIR}/version"
		;;

	*)
		echo "WPLib: You are running version $(cat "${BOX_BASE_DIR}/version")"
		;;
esac

