#!/usr/bin/env bash
#
# @todo: http://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
#

source /vagrant/scripts/guest/cli/includes/functions
source /vagrant/scripts/guest/cli/includes/constants

if [ "$1" == "" ]; then
    export WPLIB_BOX_COMMAND="help"
else
    export WPLIB_BOX_COMMAND="$1"
fi

command_file="${WPLIB_BOX_COMMANDS_DIR}/${WPLIB_BOX_COMMAND}"

if [ "${WPLIB_BOX_COMMAND}" == "help" ]; then
    source "${command_file}"
    echo
    exit
fi

if [ -f "${command_file}" ]; then
    command_type="bash"
else
    if [ -f "${command_file}.php" ]; then
        command_type="php"
    else
        echo
        echo -e "\tCommand not found: $1"
        echo
        exit
    fi
fi

echo_if_not_quiet "$*" "*Running $1..."
initial_dir=$(pwd)
case "${command_type}" in
   "bash")
        source "${command_file}" "$2" "$3" "$4" "$5"
        ;;
   "php")

        /usr/bin/php7.0 "${WPLIB_BOX_INCLUDES_DIR}/run-command.php" --args "${WPLIB_BOX_COMMAND}" "$2" "$3" "$4" "$5"
        ;;
esac
cd "${initial_dir}"
echo_if_not_quiet "$*" "*Done."
