#!/bin/sh

#this file will contain the bash script to execute any files present in the /vagrant/scripts/watchers directory

inotifywait --quiet --recursive --monitor --format "%e %w%f" \
    --event modify --event move --event create --event delete \
    /var/www | while read changed
do

    echo "$changed"

done