#!/usr/bin/env bash

export WPLIB_BOX_DIR="/vagrant"
export WPLIB_BOX_LOGS_DIR="/vagrant/logs"
export WPLIB_BOX_WEB_ROOT_DIR="/var/www"

export WPLIB_BOX_SCRIPTS_DIR="/vagrant/scripts"
export WPLIB_BOX_GUEST_DIR="/vagrant/scripts/guest"
export WPLIB_BOX_HOST_DIR="/vagrant/scripts/host"

export WPLIB_BOX_CLI_DIR="/vagrant/scripts/guest/cli"
export WPLIB_BOX_WATCHERS_DIR="/vagrant/watchers"
export WPLIB_BOX_FILES_DIR="/vagrant/scripts/files"

export WPLIB_BOX_GIT_DIR="/vagrant/.git"
export WPLIB_BOX_ORIGINAL_GIT_DIR="/vagrant/.wplib-box.git"
export WPLIB_BOX_SAVE_GIT_DIR="/vagrant/.save.git"

export WPLIB_BOX_COMMANDS_DIR="/vagrant/scripts/guest/cli/commands"
export WPLIB_BOX_INCLUDES_DIR="/vagrant/scripts/guest/cli/includes"
export WPLIB_BOX_FLAG_FILE="WPLIB_BOX_GIT_REPO"

export WPLIB_BOX_WP_CONTENT_DIR=$(find_wp_content_dir)
export WPLIB_BOX_PLUGINS_DIR=$(find_wp_plugins_dir)
export WPLIB_BOX_MU_PLUGINS_DIR=$(find_wp_mu_plugins_dir)
