#!/usr/bin/env bash

echo
echo "Setting Web Process VM to $1..."
echo

versions=( 5.6 7.0 7.1 )

# see https://www.cyberciti.biz/faq/bash-for-loop-array/
for i in "${versions[@]}"
do
    :
    if [ ! -f "/etc/init/php${1}-fpm.override" ]; then
        echo 'manual' | sudo tee /etc/init/php${i}-fpm.override 2>&1 > /dev/null
    fi

    if [ -f "/run/php/php${i}-fpm.pid" ]; then
        sudo service php${i}-fpm stop
    fi
done

sudo rm /etc/init/${1}-fpm.override
sudo service ${1}-fpm start
