#!/usr/bin/env bash
#
# `box test` sources this at the start
#

_TESTS_TOTAL=0
_TESTS_PASSED=0
_TESTS_FAILED=0

#
# `box test` calls this before running all test files
#
function testSetup() {
    source /opt/box/cli/tests/fixtures/setup
}


#
# `box test` calls this before running each test file
#
function testFileSetup() {
    unset -f setup
    unset -f teardown
}

#
# `box test` calls this before running each test file
#
function testFile() {
    if [ "" != "$(declare -F setup)" ]; then
        setup
    fi
    if [ "" != "$(declare -F teardown)" ]; then
        teardown
    fi
}

#
# `box test` calls this before running each test file
#
function testFileTeardown() {
    # delete all functions ending in "Test"
}

#
# `box test` calls this before running all test files
#
function testTeardown() {
    source /opt/box/cli/tests/fixtures/teardown
}

#
# `box test` calls this after running a test file or multiple test files
#
func testResults() {
    if [ 0 -ne $_TESTS_FAILED ] ; then
        echo "${_TESTS_FAILED} of ${_TESTS_TOTAL} tests FAILED."
        exit 1
    fi
    if [ 0 -ne $_TESTS_PASSED ] ; then
        echo "${_TESTS_PASSED} of ${_TESTS_TOTAL} tests passed."
        exit 0
    fi
}


function incr_total_tests() {
    (( _TESTS_TOTAL++ ))
}
function incr_tests_passed() {
    (( _TESTS_PASSED++ ))
}
function incr_tests_failed() {
    (( _TESTS_FAILED++ ))
}