#!/bin/bash


function setup() {
    # Run first for this file
    echo
}

function tests() {
    # A group of simple tests run here using functions found in
    # the 'box/cli/tests/includes/assertions' script tile 

    # This should succeed
    testEquals "abc" "abc"  

    # This should fail
    testEquals "abc" "xyz"  

    evalEquals "get_image_name wplib/mysql:5.5.60 60" "wplib/mysql:5.5.60"
    evalEquals "get_image_name mysql:5.5.60       60" "wplib/mysql:5.5.60"
    evalEquals "get_image_name mysql:5.5.59       60" "wplib/mysql:5.5.59"
    evalEquals "get_image_name mysql-5.5.60       60" "wplib/mysql:5.5.60"
    evalEquals "get_image_name mysql:5.5          60" "wplib/mysql:5.5.60"
    evalEquals "get_image_name mysql-5.5          60" "wplib/mysql:5.5.60"

    evalEquals "get_image_name wplib/php-fpm:7.1.17 17" "wplib/php-fpm:7.1.17"
    evalEquals "get_image_name php-fpm:7.1.17       17" "wplib/php-fpm:7.1.17"
    evalEquals "get_image_name php-fpm:7.1.16       17" "wplib/php-fpm:7.1.16"
    evalEquals "get_image_name php-fpm-7.1.17       17" "wplib/php-fpm:7.1.17"
    evalEquals "get_image_name php-fpm:7.1          17" "wplib/php-fpm:7.1.17"
    evalEquals "get_image_name php-fpm-7.1          17" "wplib/php-fpm:7.1.17"

    evalEquals "get_container_name wplib/mysql:5.5.60 60" "mysql-5.5.60"
    evalEquals "get_container_name mysql:5.5.60       60" "mysql-5.5.60"
    evalEquals "get_container_name mysql:5.5.59       60" "mysql-5.5.59"
    evalEquals "get_container_name mysql-5.5.60       60" "mysql-5.5.60"
    evalEquals "get_container_name mysql-5.5          60" "mysql-5.5.60"

    evalEquals "get_container_name wplib/php-fpm:7.1.17 17" "php-fpm-7.1.17"
    evalEquals "get_container_name php-fpm:7.1.17       17" "php-fpm-7.1.17"
    evalEquals "get_container_name php-fpm:7.1.16       17" "php-fpm-7.1.16"
    evalEquals "get_container_name php-fpm-7.1.17       17" "php-fpm-7.1.17"
    evalEquals "get_container_name php-fpm-7.1          17" "php-fpm-7.1.17"

    evalNotEmpty "box version"

}

function containerRunning_Uses() {
    # This defines one (1) provider for 'containerStartTest()'.
    # What follows is the appropriate syntax

    echo 'containerLineProvider'
    # OR
    #echo 'containerTsvProvider"
    # OR
    #echo 'containerJsonProvider'
}

function containerRunning_Test() {
    # This is an example test for testing that a container starts
    docker container ls -aq -f "status=running" "$1"
}

function containerLineProvider() {
    echo "wplib/mysql:5.5.60"
    echo "wplib/php-fpm:7.1.17"
    echo "wplib/mysql:5.5.60"
    echo "wplib/php-fpm:7.1.17"
}

function containerJsonProvider() {
    # This should output contain info in JSON format.
    # TODO write a real example
    echo '{"foo":1,"bar":2}'
}

function containerTsvProvider() {
    # This should output container info with tab-separated values by "\n"
    # TODO write a real example
    echo "Yada\tYada"
}

function teardown() {
    # Do test group-specific teardown (test group=one Bash file.)
    echo
}


