#!/usr/bin/env bash

if [ -f "$1" ]; then
    name=$(jq -r ".name" ${1})
    containername=$(jq -r ".containername" ${1})
    options=$(jq -r ".options" ${1})
    container=$(jq -r ".download" ${1})
    version=$(jq -r ".version" ${1})
    type=$(jq -r ".type" ${1})
    subtype=${type#*\/}

    case ${subtype} in
     webserver)
       source "${WPLIB_BOX_COMMANDS_DIR}/set-webserver" nginx
       ;;
     database)
       source "${WPLIB_BOX_COMMANDS_DIR}/set-database" mysql
       ;;
     processvm)
       source "${WPLIB_BOX_COMMANDS_DIR}/set-processvm" php7.0
       ;;
     kvstore)
       source "${WPLIB_BOX_COMMANDS_DIR}/set-kvstore" redis
       ;;
    esac

    echo "Removing ${containername} container..."
    docker rm ${containername} 2>&1 > /dev/null
    echo "Removing ${container}:${version:-latest} Docker image..."
    docker rmi ${container}:${version:-latest} 2>&1 > /dev/null

    for command in "${1%\/*}/commands"/*
    do
      file=${WPLIB_BOX_COMMANDS_DIR}/${command##*\/}
      if [ -f ${file} ]; then
        sudo rm ${file}
      fi
    done
fi
